[package]
name = "async-ssh2-tokio"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"
readme = "README.md"
description = "Asynchronous and easy-to-use high level ssh client library for rust."
keywords = ["async", "asynchronous", "ssh", "ssh2", "ssh client", "ssh2 client"]
categories = ["network-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
