[package]
name = "async-ssh2-tokio"
version = "0.4.0"
edition = "2021"
license-file = "LICENSE"
readme = "README.md"
description = "Asynchronous and easy-to-use high level ssh client library for rust."
keywords = ["async", "asynchronous", "ssh", "ssh2", "ssh-client"]
repository = "https://github.com/Miyoshi-Ryota/async-ssh2-tokio"
categories = ["network-programming"]
authors = ["Miyoshi-Ryota <m1yosh1.ry0t4@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
openssl = ["russh/openssl"]

[dependencies]
russh = "0.34.0-beta.16"
russh-keys = "0.22.0-beta.7"
thiserror = "1.0"

[dev-dependencies]
tokio = "1.14.0"
